#if defined _PugDB_included
	#endinput
#endif
#define _PugDB_includeds

#define SQL_HOST 		"localhost"
#define SQL_USER		"root"
#define SQL_PASSWORD 		""
#define SQL_DATABASE 		"db"
#define SQL_TIMEOUT 		0


#define SQL_TABLE_PLAYERS 	"pug_players"

#define SQL_ROW_STEAM		"steam"
#define SQL_ROW_NAME 		"name"
#define SQL_ROW_LENGTH 		"length"
#define SQL_ROW_UNBAN 		"unban"
#define SQL_ROW_REASON 		"reason"
#define SQL_ROW_BANNED 		"banned"
